# Generated by Django 4.2.4 on 2023-09-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_quantity_sellproduct_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='de1985ff5474', max_length=25),
        ),
    ]
