# Generated by Django 4.2.4 on 2023-09-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cart_products_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='08a9a0cd4ef6', max_length=25),
        ),
    ]
