# Generated by Django 4.2.4 on 2023-09-18 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_order_cart_alter_order_code_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='5909d2548ac0', max_length=25),
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_products', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('products', models.ManyToManyField(to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.cart'),
            preserve_default=False,
        ),
    ]
